# Generated by Django 6.1 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('badge_text', models.CharField(max_length=30)),
                ('badge_variant', models.CharField(default='badge-bronze', help_text='Nama class CSS, misal: badge-bronze atau badge-silver', max_length=20)),
            ],
        ),
    ]
