# Generated by Django 5.2.17 on 2026-09-13 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__gte', models.F('started_at'))), name='education_ended_at_gte_started_at')],
            },
        ),
    ]
